#!/bin/bash

version=0.2.6
confdir=/usr/share/archiso/configs
config=
options=

_usage () {
    echo "archuseriso v${version} usage:"
    echo
    echo "archuseriso <iso config> [-C|--config <path>] [build options]"
    echo
    echo "help:"
    echo "archuseriso -h"
    echo
    echo "iso config help:"
    echo "archuseriso <iso config> -h"
    echo
    echo "iso config list, select one from:"
    echo "* console"
    echo "* cinnamon"
    echo "* deepin"
    echo "* gnome"
    echo "* kde"
    echo "* mate"
    echo "* xfce"
    echo
    echo "Build examples:"
    echo "archuseriso kde"
    echo "archuseriso kde -l fr"
    exit ${1}
}

_help () {
    echo "The archuseriso program is a wrapper"
    echo "which executes the corresponding iso's"
    echo "config build script."
    echo "You may directly run the config's"
    echo "build script \`build.sh\` instead."
    echo
    echo "Synopsis:"
    echo "archuseriso <iso config> [-C|--config <path>] [build options]"
    echo
    echo "-C, --confdir <path>"
    echo "    Path to configs directory (default: /usr/share/archiso/configs)"
    echo
    echo "iso config list, select one from:"
    echo "* console"
    echo "* cinnnamon"
    echo "* deepin"
    echo "* gnome"
    echo "* kde"
    echo "* mate"
    echo "* xfce"
    echo
    echo "Build examples:"
    echo "archuseriso kde"
    echo "archuseriso kde -l fr"
    echo
    echo "To list the build script options:"
    echo "archuseriso <iso config> -h"
    echo
    echo "or run the config's build script:"
    echo "<path>/build.sh -h"
    echo
    echo "To customize an iso config:"
    echo "cp -rL /usr/share/archiso/configs/<config> <destination>"
    echo
    echo "Edit packages files located in <config> and <config>/lang/<locale>."
    echo "Add your packages files to <config>/pkglocal."
    echo "Then run the config's build script \`build.sh\`."
    exit ${1}
}


if [[ ${EUID} -ne 0 ]]; then
    echo "This script must be run as root."
    echo
    echo "help:"
    echo "archuseriso -h"
    exit 1
fi

if [[ "$1" == '-h' ]]; then
  _help 0
fi

case "$1" in
    console)
        config="console"
        shift ;;
    cinnamon)
        config="cinnamon"
        shift ;;
    deepin)
        config="deepin"
        shift ;;
    gnome)
        config="gnome"
        shift ;;
    kde)
        config="kde"
        shift ;;
    mate)
        config="mate"
        shift ;;
    xfce)
        config="xfce"
        shift ;;
    *)
        _usage 1 ;;
esac

OPTS=$(getopt -o 'A:C:D:L:N:P:V:c:g:hl:o:w:v' --long 'confdir:,help' -n 'archuseriso' -- "$@")
eval set -- "${OPTS}"

[[ "$?" -eq 0 ]] || _usage 1
unset OPTS

while true; do
    case "$1" in
        '-C'|'--confdir')
            confdir="$2"
            shift 2 ;;
        '-A'|'-D'|'-L'|'-N'|'-P'|'-V'|'-c'|'-g'|'-l'|'-o'|'-w')
            options+="$1 $2 "
            shift 2 ;;
        '-h'|'--help')
            options="-h"
            shift
            break ;;
        '-v')
            options+="-v "
            shift ;;
        '--')
            shift
            break ;;
        *)
            shift
            echo "Invalid argument ${arg}"
            _usage 1 ;;
    esac
done

# Run the build script:
eval "${confdir}/${config}/build.sh ${options}"
