#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e -u

# Control the environment
umask 0022
export LANG="C"
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-"$(date +%s)"}"
SCRIPTUSER="${SUDO_USER:-}"

# Set application name from the script's file name
app_name="${0##*/}"

# Global variables.
airootfs_image_type="squashfs"
airootfs_image_tool_options=()
arch="$(uname -m)"
bootmodes=()
build_zfs_packages="n"
directory_profiles="/usr/share/archuseriso/profiles"
desktop=""
embed_dir=""
gpg_key=""
img_name=""
install_dir=""
iso_application=""
iso_label=""
iso_name="${app_name}"
iso_publisher=""
iso_version=""
iso_version_options=()
lang=""
out_dir=""
packages=""
packages_locales=""
pacman_conf=""
pacman_testing_conf=""
pkg_list=()
pkg_list_additions=()
pkg_testing_list=()
profile=""
quiet=""
user_pkg_dir=""
work_dir=""
declare -A file_permissions=()

# Show an INFO message
# $1: message string
_msg_info() {
    local _msg="${1}"
    printf '[%s] INFO: %s\n' "${app_name}" "${_msg}"
}

# Show a WARNING message
# $1: message string
_msg_warning() {
    local _msg="${1}"
    printf '[%s] WARNING: %s\n' "${app_name}" "${_msg}" >&2
}

# Show an ERROR message then exit with status
# $1: message string
# $2: exit code number (with 0 does not exit)
_msg_error() {
    local _msg="${1}"
    local _error=${2}
    printf '[%s] ERROR: %s\n' "${app_name}" "${_msg}" >&2
    if (( _error > 0 )); then
        exit "${_error}"
    fi
}

_mount_airootfs() {
    trap "_umount_airootfs" EXIT HUP INT TERM
    install -d -m 0755 -- "${work_dir}/mnt/airootfs"
	_msg_info "Mounting '${airootfs_dir}.img' on '${work_dir}/mnt/airootfs'..."
    mount -- "${airootfs_dir}.img" "${work_dir}/mnt/airootfs"
    _msg_info "Done!"
}

_umount_airootfs() {
    _msg_info "Unmounting '${work_dir}/mnt/airootfs'..."
    umount -d -- "${work_dir}/mnt/airootfs"
    _msg_info "Done!"
    rmdir -- "${work_dir}/mnt/airootfs"
    trap - EXIT HUP INT TERM
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
    IFS='' read -r -d '' usagetext <<ENDUSAGETEXT || true
usage: ${app_name} [options] <profile_dir>
  options:
     -A, --application  <application>   Set an application name for the ISO
                                        Default: '${iso_application}'
     --add-pkg, -p     PACKAGE(S)       Package(s) to install, comma seperated list
     --add-pkg-testing PACKAGE(S)       Package(s) to install from testing repositories,
                                        comma seperated list
     --add-i3-wm                        Add i3wm packages: i3-gaps,feh,dmenu,i3status,wmctrl
     -C <file>                          pacman configuration file.
                                        Default: '${pacman_conf}'
     -D, --install-dir  <install_dir>   Set an install_dir. All files will by located here.
                                        Default: '${install_dir}'
                                        NOTE: Max 8 characters, use only [a-z0-9]
     --embed-dir <path>                 Embed directory contents in the iso image,
                                        data available from the live's session.
     -g <gpg_key>                       Set the GPG key to be used for signing the sqashfs image
     -h                                 This message
     -L <label>                         Set the ISO volume label
                                        Default: '${iso_label}'
     -l, --language <lang>              Set default language, select one from:
                                        cz, de, es, fr, gr, hu, it, nl, pl, pt, ro, rs, ru, tr, ua
     --nvidia                           Nvidia graphics driver setup
     --optimus                          For Optimus hardware, set Intel iGPU default and Nvidia dGPU
                                        configured for PRIME render offload (prime-run <application>)
     -o <out_dir>                       Set the output directory
                                        Default: '${out_dir}'
     --pacman-testing-conf <file>       pacman configuration file with testing repositories enabled.
                                        Default: '${pacman_testing_conf}'
     --pkg-dir <path>                   Directory containing user packages to install,
                                        pkg.tar.xz or pkg.tar.zst package files.
     -P <publisher>                     Set the ISO publisher
                                        Default: '${iso_publisher}'
     -v, --verbose                      Enable verbose output
     -w, --work-dir <work_dir>          Set the working directory
                                        Default: '${work_dir}'
     --zfs                              Dynamically builds the ZFS packages against installed
                                        kernel and install packages.

  profile_dir:        Directory of the archuseriso profile to build. Available directory profiles
                      under /usr/share/archuseriso/profiles

  Build example:
  sudo ${app_name} /usr/share/archuseriso/profiles/xfce

  Customization:
  Copy the directory profile to an new location then edit profiledef.sh and packages.x86_64
                     

ENDUSAGETEXT
    printf '%s' "${usagetext}"
    exit "${1}"
}

# Shows configuration options.
_show_config() {
    local build_date
    build_date="$(date --utc --iso-8601=seconds -d "@${SOURCE_DATE_EPOCH}")"
    _msg_info "${app_name} configuration settings"
    _msg_info "             Architecture:   ${arch}"
    _msg_info "        Working directory:   ${work_dir}"
    _msg_info "   Installation directory:   ${install_dir}"
    _msg_info "               Build date:   ${build_date}"
    _msg_info "         Output directory:   ${out_dir}"
    _msg_info "                  GPG key:   ${gpg_key:-None}"
    _msg_info "                  Profile:   ${profile}"
    _msg_info "Pacman configuration file:   ${pacman_conf}"
    _msg_info "Pacman testing conf. file:   ${pacman_testing_conf}"
    _msg_info "         ISO volume label:   ${iso_label}"
    _msg_info "            ISO publisher:   ${iso_publisher}"
    _msg_info "          ISO application:   ${iso_application}"
    _msg_info "               Boot modes:   ${bootmodes[*]}"
    _msg_info "    Packages from testing:   ${pkg_testing_list[*]}"
    _msg_info "  User packages directory:   ${user_pkg_dir}"
    _msg_info "                 Packages:   ${pkg_list[*]}"
}

# Cleanup airootfs
_cleanup_airootfs() {
    _msg_info "Cleaning up what we can on airootfs..."

    # Delete all files in /boot
    [[ -d "${airootfs_dir}/boot" ]] && find "${airootfs_dir}/boot" -mindepth 1 -delete
    # Delete pacman database sync cache files (*.tar.gz)
    [[ -d "${airootfs_dir}/var/lib/pacman" ]] && find "${airootfs_dir}/var/lib/pacman" -maxdepth 1 -type f -delete
    # Delete pacman database sync cache
    [[ -d "${airootfs_dir}/var/lib/pacman/sync" ]] && find "${airootfs_dir}/var/lib/pacman/sync" -delete
    # Delete pacman package cache
    [[ -d "${airootfs_dir}/var/cache/pacman/pkg" ]] && find "${airootfs_dir}/var/cache/pacman/pkg" -type f -delete
    # Delete all log files, keeps empty dirs.
    [[ -d "${airootfs_dir}/var/log" ]] && find "${airootfs_dir}/var/log" -type f -delete
    # Delete all temporary files and dirs
    [[ -d "${airootfs_dir}/var/tmp" ]] && find "${airootfs_dir}/var/tmp" -mindepth 1 -delete
    # Delete package pacman related files.
    find "${work_dir}" \( -name '*.pacnew' -o -name '*.pacsave' -o -name '*.pacorig' \) -delete
    # Create an empty /etc/machine-id
    printf '' > "${airootfs_dir}/etc/machine-id"

    _msg_info "Done!"
}

_run_mksquashfs() {
    # Set default mksquashfs options
    if (( ${#airootfs_image_tool_options[@]} < 1 )); then
        airootfs_image_tool_options=('-comp' 'zstd')
    fi
    local image_path="${isofs_dir}/${install_dir}/${arch}/airootfs.sfs"
    if [[ "${quiet}" == "y" ]]; then
        mksquashfs "$@" "${image_path}" -noappend "${airootfs_image_tool_options[@]}" -no-progress &> /dev/null
    else
        mksquashfs "$@" "${image_path}" -noappend "${airootfs_image_tool_options[@]}"
    fi
}

# Makes a ext4 filesystem inside a SquashFS from a source directory.
_mkairootfs_ext4+squashfs() {
    [[ -e "${airootfs_dir}" ]] || _msg_error "The path '${airootfs_dir}' does not exist" 1

    _msg_info "Creating ext4 image of 32 GiB..."
    if [[ "${quiet}" == "y" ]]; then
        mkfs.ext4 -q -O '^has_journal,^resize_inode' -E 'lazy_itable_init=0' -m 0 -F -- "${airootfs_dir}.img" 32G
    else
        mkfs.ext4 -O '^has_journal,^resize_inode' -E 'lazy_itable_init=0' -m 0 -F -- "${airootfs_dir}.img" 32G
    fi
    tune2fs -c 0 -i 0 -- "${airootfs_dir}.img" > /dev/null
    _msg_info "Done!"
    _mount_airootfs
    _msg_info "Copying '${airootfs_dir}/' to '${work_dir}/mnt/airootfs/'..."
    cp -aT -- "${airootfs_dir}/" "${work_dir}/mnt/airootfs/"
    chown -- 0:0 "${work_dir}/mnt/airootfs/"
    _msg_info "Done!"
    _umount_airootfs
    install -d -m 0755 -- "${isofs_dir}/${install_dir}/${arch}"
    echo
    _msg_info "Creating SquashFS image, this may take some time..."
    _run_mksquashfs "${airootfs_dir}.img"
    _msg_info "Done!"
    rm -- "${airootfs_dir}.img"
}

# Makes a SquashFS filesystem from a source directory.
_mkairootfs_squashfs() {
    if [[ ! -e "${airootfs_dir}" ]]; then
        _msg_error "The path '${airootfs_dir}' does not exist" 1
    fi

    install -d -m 0755 -- "${isofs_dir}/${install_dir}/${arch}"
    echo
    _msg_info "Creating SquashFS image, this may take some time..."
    _run_mksquashfs "${airootfs_dir}"
    _msg_info "Done!"
}

_mkchecksum() {
    _msg_info "Creating checksum file for self-test..."
    cd -- "${isofs_dir}/${install_dir}/${arch}"
    sha512sum airootfs.sfs > airootfs.sha512
    cd -- "${OLDPWD}"
    _msg_info "Done!"
}

_mksignature() {
    _msg_info "Signing SquashFS image..."
    cd -- "${isofs_dir}/${install_dir}/${arch}"
    gpg --detach-sign --default-key "${gpg_key}" airootfs.sfs
    cd -- "${OLDPWD}"
    _msg_info "Done!"
}

_mkchecksum_iso() {
    _msg_info "Creating iso image checksum file..."
    cd -- "${out_dir}"
    sha512sum "${img_name}" > "${img_name}.sha512"
    cd -- "${OLDPWD}"
    _msg_info "Done!"
}

_mksignature_iso() {
    _msg_info "Signing iso image..."
    cd -- "${out_dir}"
    gpg --detach-sign --default-key "${gpg_key}" "${img_name}"
    cd -- "${OLDPWD}"
    _msg_info "Done!"
}

# Helper function to run functions only one time.
_run_once() {
    if [[ ! -e "${work_dir}/build.${1}" ]]; then
        "$1"
        touch "${work_dir}/build.${1}"
    fi
}

# Set up custom pacman.conf with custom cache and pacman hook directories.
_make_pacman_conf() {
    local _cache_dirs _system_cache_dirs _profile_cache_dirs
    _system_cache_dirs="$(pacman-conf CacheDir| tr '\n' ' ')"
    _profile_cache_dirs="$(pacman-conf --config "${pacman_conf}" CacheDir| tr '\n' ' ')"

    # only use the profile's CacheDir, if it is not the default and not the same as the system cache dir
    if [[ "${_profile_cache_dirs}" != "/var/cache/pacman/pkg" ]] && \
        [[ "${_system_cache_dirs}" != "${_profile_cache_dirs}" ]]; then
        _cache_dirs="${_profile_cache_dirs}"
    else
        _cache_dirs="${_system_cache_dirs}"
    fi

    echo
    _msg_info "Copying custom pacman.conf to work directory..."
    # take the profile pacman.conf and strip all settings that would break in chroot when using pacman -r
    # see `man 8 pacman` for further info
    pacman-conf --config "${pacman_conf}" | \
        sed '/CacheDir/d;/DBPath/d;/HookDir/d;/LogFile/d;/RootDir/d' > "${work_dir}/pacman.conf"
    _msg_info "Done!"

    _msg_info "Using pacman CacheDir: ${_cache_dirs}"
    # append CacheDir and HookDir to [options] section
    # HookDir is *always* set to the airootfs' override directory
    sed "/\[options\]/a CacheDir = ${_cache_dirs}
        /\[options\]/a HookDir = ${airootfs_dir}/etc/pacman.d/hooks/" \
        -i "${work_dir}/pacman.conf"
    _msg_info "Done!"
}

# Set up custom pacman-testing.conf with custom cache and pacman hook directories.
_make_pacman_testing_conf() {
    local _cache_dirs _system_cache_dirs _profile_cache_dirs
    _system_cache_dirs="$(pacman-conf CacheDir| tr '\n' ' ')"
    _profile_cache_dirs="$(pacman-conf --config "${pacman_testing_conf}" CacheDir| tr '\n' ' ')"

    # only use the profile's CacheDir, if it is not the default and not the same as the system cache dir
    if [[ "${_profile_cache_dirs}" != "/var/cache/pacman/pkg" ]] && \
        [[ "${_system_cache_dirs}" != "${_profile_cache_dirs}" ]]; then
        _cache_dirs="${_profile_cache_dirs}"
    else
        _cache_dirs="${_system_cache_dirs}"
    fi

    _msg_info "Copying custom pacman-testing.conf to work directory..."
    # take the profile pacman-testing.conf and strip all settings that would break in chroot when using pacman -r
    # see `man 8 pacman` for further info
    pacman-conf --config "${pacman_testing_conf}" | \
        sed '/CacheDir/d;/DBPath/d;/HookDir/d;/LogFile/d;/RootDir/d' > "${work_dir}/pacman-testing.conf"
    _msg_info "Done!"

    _msg_info "Using pacman CacheDir: ${_cache_dirs}"
    # append CacheDir and HookDir to [options] section
    # HookDir is *always* set to the airootfs' override directory
    sed "/\[options\]/a CacheDir = ${_cache_dirs}
        /\[options\]/a HookDir = ${airootfs_dir}/etc/pacman.d/hooks/" \
        -i "${work_dir}/pacman-testing.conf"
    _msg_info "Done!"
}

# Prepare working directory and copy custom airootfs files (airootfs)
_make_custom_airootfs() {
    local passwd=()
    local filename permissions

    install -d -m 0755 -o 0 -g 0 -- "${airootfs_dir}"

    if [[ -d "${profile}/airootfs" ]]; then
        _msg_info "Copying custom airootfs files..."
        cp -af --no-preserve=ownership -- "${profile}/airootfs/." "${airootfs_dir}"
        # airootfs localization
        if [[ -n "${lang}" ]]; then
            cp -af --no-preserve=ownership -- "${profile}/lang/${lang}/airootfs/." "${airootfs_dir}"
        fi
        # Set ownership and mode for files and directories
        for filename in "${!file_permissions[@]}"; do
            IFS=':' read -ra permissions <<< "${file_permissions["${filename}"]}"
            # Prevent file path traversal outside of $airootfs_dir
            if [[ "$(realpath -q -- "${airootfs_dir}${filename}")" != "${airootfs_dir}"* ]]; then
                _msg_error "Failed to set permissions on '${airootfs_dir}${filename}'. Outside of valid path." 1
            # Warn if the file does not exist
            elif [[ ! -e "${airootfs_dir}${filename}" ]]; then
                _msg_warning "Cannot change permissions of '${airootfs_dir}${filename}'. The file or directory does not exist."
            else
                chown -fh -- "${permissions[0]}:${permissions[1]}" "${airootfs_dir}${filename}"
                chmod -f -- "${permissions[2]}" "${airootfs_dir}${filename}"
            fi
        done
    fi

    # Set archiso cow_spacesize to 50% ram size
    sed -i 's|\(cow_spacesize=\)"256M"|\1"$(( $(awk \x27/MemTotal:/ { print $2 }\x27 /proc/meminfo) / 2 / 1024 ))M"|' \
        "${work_dir}/x86_64/airootfs/etc/initcpio/hooks/archiso"
    _msg_info "Done!"
}

# Install desired packages to airootfs
_make_packages() {
     _msg_info "Installing packages to '${airootfs_dir}/'..."

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<>"${work_dir}/pubkey.gpg"
        export ARCHISO_GNUPG_FD
    fi
    if [[ "${quiet}" = "y" ]]; then
        pacstrap -C "${work_dir}/pacman.conf" -c -G -M -- "${airootfs_dir}" "${pkg_list[@]}" &> /dev/null
    else
        pacstrap -C "${work_dir}/pacman.conf" -c -G -M -- "${airootfs_dir}" "${pkg_list[@]}"
    fi

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<&-
        unset ARCHISO_GNUPG_FD
    fi

    _msg_info "Done!"
}

# Packages in testing (airootfs)
_make_packages_testing () {
    _msg_info "Installing testing packages to '${airootfs_dir}/'..."

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<>"${work_dir}/pubkey.gpg"
        export ARCHISO_GNUPG_FD
    fi

    if [[ "${quiet}" = "y" ]]; then
        pacstrap -C "${work_dir}/pacman-testing.conf" -c -G -M -- "${airootfs_dir}" "${pkg_testing_list[@]}" &> /dev/null
    else
        pacstrap -C "${work_dir}/pacman-testing.conf" -c -G -M -- "${airootfs_dir}" "${pkg_testing_list[@]}"
    fi

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<&-
        unset ARCHISO_GNUPG_FD
    fi

    _msg_info "Done!"
}

# airootfs install user provided packages
_make_packages_upgrade() {
    local _pkg_upgrade
    mapfile -t _pkg_upgrade < <(find "${user_pkg_dir}" -maxdepth 1 \( -name "*.pkg.tar.xz" -o -name "*.pkg.tar.zst" \))

    _msg_info "Installing user packages to '${airootfs_dir}/'..."

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<>"${work_dir}/pubkey.gpg"
        export ARCHISO_GNUPG_FD
    fi

    if [[ "${quiet}" = "y" ]]; then
        pacstrap -C "${work_dir}/pacman.conf" -c -G -M -U -- "${airootfs_dir}" "${_pkg_upgrade[@]}" &> /dev/null
    else
        pacstrap -C "${work_dir}/pacman.conf" -c -G -M -U -- "${airootfs_dir}" "${_pkg_upgrade[@]}"
    fi

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<&-
        unset ARCHISO_GNUPG_FD
    fi

    _msg_info "Done!"
}

# Customize installation (airootfs)
_make_customize_airootfs() {
    local passwd=()

    # Set up user home directories and permissions
    if [[ -e "${profile}/airootfs/etc/passwd" ]]; then
        _msg_info "Copying /etc/skel/* to user homes..."
        while IFS=':' read -a passwd -r; do
            # Only operate on UIDs in range 1000–59999
            (( passwd[2] >= 1000 && passwd[2] < 60000 )) || continue
            # Skip invalid home directories
            [[ "${passwd[5]}" == '/' ]] && continue
	        [[ -z "${passwd[5]}" ]] && continue
            # Prevent path traversal outside of $airootfs_dir
            if [[ "$(realpath -q -- "${airootfs_dir}${passwd[5]}")" == "${airootfs_dir}"* ]]; then
                if [[ ! -d "${airootfs_dir}${passwd[5]}" ]]; then
                    install -d -m 0750 -o "${passwd[2]}" -g "${passwd[3]}" -- "${airootfs_dir}${passwd[5]}"
                fi
                cp -dnRT --preserve=mode,timestamps,links -- "${airootfs_dir}/etc/skel/." "${airootfs_dir}${passwd[5]}"
                chown -hR -- "${passwd[2]}:${passwd[3]}" "${airootfs_dir}${passwd[5]}"
            else
                _msg_error "Failed to set permissions on '${airootfs_dir}${passwd[5]}'. Outside of valid path." 1
            fi
        done < "${profile}/airootfs/etc/passwd" 
        _msg_info "Done!"
    fi

    if [[ -e "${airootfs_dir}/root/customize_airootfs_lang.sh" ]]; then
        _msg_info "Running customize_airootfs_lang.sh in '${airootfs_dir}' chroot..."
        chmod -f -- +x "${airootfs_dir}/root/customize_airootfs_lang.sh"
        if [[ "${quiet}" == "y" ]]; then
            arch-chroot "${airootfs_dir}" "/root/customize_airootfs_lang.sh" &> /dev/null
        else
            arch-chroot "${airootfs_dir}" "/root/customize_airootfs_lang.sh"
        fi
        rm -- "${airootfs_dir}/root/customize_airootfs_lang.sh"
        _msg_info "Done!"
    fi
    if [[ -e "${airootfs_dir}/root/customize_airootfs.sh" ]]; then
        _msg_info "Running customize_airootfs.sh in '${airootfs_dir}' chroot..."
        chmod -f -- +x "${airootfs_dir}/root/customize_airootfs.sh"
        if [[ "${quiet}" == "y" ]]; then
            arch-chroot "${airootfs_dir}" "/root/customize_airootfs.sh" &> /dev/null
        else
            arch-chroot "${airootfs_dir}" "/root/customize_airootfs.sh"
        fi
        rm -- "${airootfs_dir}/root/customize_airootfs.sh"
        _msg_info "Done!"
    fi
}

# rebuild initramfs (airootfs)
_make_setup_mkinitcpio() {
    if [[ "${iso_version}" =~ (nvidia|optimus) ]]; then
        # add nvidia modules to initramfs
        sed -i 's/MODULES=(/&nvidia nvidia_drm nvidia_modeset/' "${airootfs_dir}/etc/mkinitcpio.conf"
    fi
    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<>"${work_dir}/pubkey.gpg"
        export ARCHISO_GNUPG_FD
    fi

    if [[ "${quiet}" = "y" ]]; then
        arch-chroot "${airootfs_dir}" mkinitcpio -P &> /dev/null
    else
        arch-chroot "${airootfs_dir}" mkinitcpio -P
    fi

    if [[ -n "${gpg_key}" ]]; then
        exec {ARCHISO_GNUPG_FD}<&-
        unset ARCHISO_GNUPG_FD
    fi
}

# Set up boot loaders
_make_bootmodes() {
    local bootmode
    for bootmode in "${bootmodes[@]}"; do
        _run_once "_make_bootmode_${bootmode}"
    done
}

# Prepare kernel/initramfs ${install_dir}/boot/
_make_boot_on_iso9660() {
    _msg_info "Preparing kernel and initramfs for the ISO 9660 file system..."
    install -d -m 0755 -- "${isofs_dir}/${install_dir}/boot/${arch}"
    install -m 0644 -- "${airootfs_dir}/boot/initramfs-"*".img" "${isofs_dir}/${install_dir}/boot/${arch}/"
    install -m 0644 -- "${airootfs_dir}/boot/vmlinuz-"* "${isofs_dir}/${install_dir}/boot/${arch}/"

    for _ucode_image in {intel-uc.img,intel-ucode.img,amd-uc.img,amd-ucode.img,early_ucode.cpio,microcode.cpio}; do
        if [[ -e "${airootfs_dir}/boot/${_ucode_image}" ]]; then
            install -m 0644 -- "${airootfs_dir}/boot/${_ucode_image}" "${isofs_dir}/${install_dir}/boot/"
            if [[ -e "${airootfs_dir}/usr/share/licenses/${_ucode_image%.*}/" ]]; then
                install -d -m 0755 -- "${isofs_dir}/${install_dir}/boot/licenses/${_ucode_image%.*}/"
                install -m 0644 -- "${airootfs_dir}/usr/share/licenses/${_ucode_image%.*}/"* \
                    "${isofs_dir}/${install_dir}/boot/licenses/${_ucode_image%.*}/"
            fi
        fi
    done
    _msg_info "Done!"
}

# Prepare /syslinux for booting from MBR
_make_bootmode_bios.syslinux.mbr() {
    _msg_info "Setting up SYSLINUX for BIOS booting from a disk..."
    install -d -m 0755 -- "${isofs_dir}/syslinux"
    for _cfg in "${profile}/syslinux/"*.cfg; do
        sed "s|%DESKTOP%|${desktop}|g;
             s|%ARCHISO_LABEL%|${iso_label}|g;
             s|%INSTALL_DIR%|${install_dir}|g;
             s|%ARCH%|${arch}|g" \
             "${_cfg}" > "${isofs_dir}/syslinux/${_cfg##*/}"
    done
    if [[ -e "${profile}/syslinux/splash.png" ]]; then
        install -m 0644 -- "${profile}/syslinux/splash.png" "${isofs_dir}/syslinux/"
    fi
    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/lib/syslinux/bios/"*.c32 "${isofs_dir}/syslinux/"
    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/lib/syslinux/bios/lpxelinux.0" "${isofs_dir}/syslinux/"
    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/lib/syslinux/bios/memdisk" "${isofs_dir}/syslinux/"

    _run_once _make_boot_on_iso9660

    if [[ -e "${isofs_dir}/syslinux/hdt.c32" ]]; then
        install -d -m 0755 -- "${isofs_dir}/syslinux/hdt"
        if [[ -e "${airootfs_dir}/usr/share/hwdata/pci.ids" ]]; then
            gzip -c -9 "${airootfs_dir}/usr/share/hwdata/pci.ids" > \
                "${isofs_dir}/syslinux/hdt/pciids.gz"
        fi
        find "${airootfs_dir}/usr/lib/modules" -name 'modules.alias' -print -exec gzip -c -9 '{}' ';' -quit > \
            "${isofs_dir}/syslinux/hdt/modalias.gz"
    fi

    # Add other aditional/extra files to ${install_dir}/boot/
    if [[ -e "${airootfs_dir}/boot/memtest86+/memtest.bin" ]]; then
        # rename for PXE: https://wiki.archlinux.org/index.php/Syslinux#Using_memtest
        install -m 0644 -- "${airootfs_dir}/boot/memtest86+/memtest.bin" "${isofs_dir}/${install_dir}/boot/memtest"
        install -d -m 0755 -- "${isofs_dir}/${install_dir}/boot/licenses/memtest86+/" 
        install -m 0644 -- "${airootfs_dir}/usr/share/licenses/common/GPL2/license.txt" \
            "${isofs_dir}/${install_dir}/boot/licenses/memtest86+/"
    fi
    _msg_info "Done!"
}

# Prepare /syslinux for El-Torito booting
_make_bootmode_bios.syslinux.eltorito() {
    _msg_info "Setting up SYSLINUX for BIOS booting from an optical disc..."
    install -d -m 0755 -- "${isofs_dir}/syslinux"
    install -m 0644 -- "${airootfs_dir}/usr/lib/syslinux/bios/isolinux.bin" "${isofs_dir}/syslinux/"
    install -m 0644 -- "${airootfs_dir}/usr/lib/syslinux/bios/isohdpfx.bin" "${isofs_dir}/syslinux/"

    # ISOLINUX and SYSLINUX installation is shared
    _run_once _make_bootmode_bios.syslinux.mbr

    _msg_info "Done!"
}

# Prepare /EFI on ISO-9660
_make_efi_dir_on_iso9660() {
    _msg_info "Preparing an /EFI directory for the ISO 9660 file system..."
    install -d -m 0755 -- "${isofs_dir}/EFI/BOOT"
    install -d -m 0755 -- "${isofs_dir}/EFI/live"
    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/share/refind/refind_x64.efi" "${isofs_dir}/EFI/BOOT/BOOTx64.efi"
    cp -a -- "${work_dir}"/x86_64/airootfs/usr/share/refind/{drivers_x64,icons}/ "${isofs_dir}/EFI/BOOT/"

    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/lib/systemd/boot/efi/systemd-bootx64.efi" "${isofs_dir}/EFI/live/livedisk.efi"
    install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/share/refind/icons/os_arch.png" "${isofs_dir}/EFI/live/livedisk.png"

    install -m 0644 -- "${profile}/efiboot/boot/refind-usb.conf" "${isofs_dir}/EFI/BOOT/refind.conf"

    install -d -m 0755 -- "${isofs_dir}/loader/entries"
    install -m 0644 -- "${profile}/efiboot/loader/loader.conf" "${isofs_dir}/loader/"
    for _entry in  "${profile}/efiboot/loader/entries/"*".conf"; do
        install -m 0644 -- "${_entry}" "${isofs_dir}/loader/entries/${_entry##*/}"
    done

    for _conf in "${profile}/efiboot/loader/entries/"*".conf"; do
        sed "s|%DESKTOP%|${desktop}|g;
             s|%ARCHISO_LABEL%|${iso_label}|g;
             s|%INSTALL_DIR%|${install_dir}|g;
             s|%ARCH%|${arch}|g" \
             "${_conf}" > "${isofs_dir}/loader/entries/${_conf##*/}"
    done

    # EFI Shell 2.0 for UEFI 2.3+
    # shellx64.efi is picked up automatically when on /
    if [[ -e "${airootfs_dir}/usr/share/edk2-shell/x64/Shell_Full.efi" ]]; then
        install -m 0644 -- "${work_dir}/x86_64/airootfs/usr/share/edk2-shell/x64/Shell_Full.efi" "${isofs_dir}/shellx64.efi"
    fi
    _msg_info "Done!"
}

# Prepare kernel/initramfs on efiboot.img
_make_boot_on_fat() {
    _msg_info "Preparing kernel and initramfs for the FAT file system..."
    mmd -i "${work_dir}/efiboot.img" \
        "::/${install_dir}" "::/${install_dir}/boot" "::/${install_dir}/boot/${arch}"
    mcopy -i "${work_dir}/efiboot.img" "${airootfs_dir}/boot/vmlinuz-"* \
        "${airootfs_dir}/boot/initramfs-"*".img" "::/${install_dir}/boot/${arch}/"
    for _ucode_image in \
        "${airootfs_dir}/boot/"{intel-uc.img,intel-ucode.img,amd-uc.img,amd-ucode.img,early_ucode.cpio,microcode.cpio}
    do
        if [[ -e "${_ucode_image}" ]]; then
            _all_ucode_images+=("${_ucode_image}")
        fi
    done
    if (( ${#_all_ucode_images[@]} )); then
        mcopy -i "${work_dir}/efiboot.img" "${_all_ucode_images[@]}" "::/${install_dir}/boot/"
    fi
    _msg_info "Done!"
}

# Prepare efiboot.img::/EFI for EFI boot mode
_make_bootmode_uefi-x64.systemd-boot.esp() {
    local _efiboot_imgsize="0"
    _msg_info "Setting up systemd-boot for UEFI booting..."

    # the required image size in KiB (rounded up to the next full MiB with an additional MiB for reserved sectors)
    _efiboot_imgsize="$(du -bc \
        "${airootfs_dir}/usr/lib/systemd/boot/efi/systemd-bootx64.efi" \
        "${airootfs_dir}/usr/share/edk2-shell/x64/Shell_Full.efi" \
        "${profile}/efiboot/" \
        "${airootfs_dir}/boot/vmlinuz-"* \
        "${airootfs_dir}/boot/initramfs-"*".img" \
        "${airootfs_dir}/boot/"{intel-uc.img,intel-ucode.img,amd-uc.img,amd-ucode.img,early_ucode.cpio,microcode.cpio} \
        "${airootfs_dir}/usr/share/refind" \
        2>/dev/null | awk 'function ceil(x){return int(x)+(x>int(x))}
                           function byte_to_kib(x){return x/1024}
                           function mib_to_kib(x){return x*1024}
                           END {print mib_to_kib(ceil((byte_to_kib($1)+1024)/1024))}'
                    )"
    # The FAT image must be created with mkfs.fat not mformat, as some
    # systems have issues with mformat made images:
    # https://lists.gnu.org/archive/html/grub-devel/2019-04/msg00099.html
    [[ -e "${work_dir}/efiboot.img" ]] && rm -f -- "${work_dir}/efiboot.img"
    _msg_info "Creating FAT image of size: ${_efiboot_imgsize} KiB..."
    if [[ "${quiet}" == "y" ]]; then
        mkfs.fat -C -n LIVEMEDIUM "${work_dir}/efiboot.img" "${_efiboot_imgsize}" &> /dev/null
    else
        mkfs.fat -C -n LIVEMEDIUM "${work_dir}/efiboot.img" "${_efiboot_imgsize}"
    fi
    _msg_info "Done!"

    mmd -i "${work_dir}/efiboot.img" \
           ::/EFI ::/EFI/BOOT ::/EFI/BOOT/drivers_x64 ::/EFI/BOOT/icons ::/EFI/live \
           ::/loader ::/loader/entries
    mcopy -i "${work_dir}/efiboot.img" \
             "${work_dir}/x86_64/airootfs/usr/share/refind/refind_x64.efi" ::/EFI/BOOT/BOOTx64.EFI
    mcopy -i "${work_dir}/efiboot.img" \
             "${work_dir}"/x86_64/airootfs/usr/share/refind/drivers_x64/* ::/EFI/BOOT/drivers_x64/
    mcopy -i "${work_dir}/efiboot.img" \
             "${work_dir}"/x86_64/airootfs/usr/share/refind/icons/* ::/EFI/BOOT/icons/
    mcopy -i "${work_dir}/efiboot.img" \
             "${work_dir}/x86_64/airootfs/usr/lib/systemd/boot/efi/systemd-bootx64.efi" ::/EFI/live/livedvd.efi
    mcopy -i "${work_dir}/efiboot.img" \
             "${work_dir}/x86_64/airootfs/usr/share/refind/icons/os_arch.png" ::/EFI/live/livedvd.png
    mcopy -i "${work_dir}/efiboot.img" \
             "${profile}/efiboot/boot/refind-dvd.conf" ::/EFI/BOOT/refind.conf
    mcopy -i "${work_dir}/efiboot.img" \
             "${profile}/efiboot/loader/loader.conf" ::loader/

    for _conf in "${profile}/efiboot/loader/entries/"*".conf"; do
        sed "s|%DESKTOP%|${desktop}|g;
             s|%ARCHISO_LABEL%|${iso_label}|g;
             s|%INSTALL_DIR%|${install_dir}|g;
             s|%ARCH%|${arch}|g" \
             "${_conf}" | mcopy -i "${work_dir}/efiboot.img" - "::/loader/entries/${_conf##*/}"
    done

    # shellx64.efi is picked up automatically when on /
    if [[ -e "${airootfs_dir}/usr/share/edk2-shell/x64/Shell_Full.efi" ]]; then
        mcopy -i "${work_dir}/efiboot.img" \
            "${airootfs_dir}/usr/share/edk2-shell/x64/Shell_Full.efi" ::/shellx64.efi
    fi

    _msg_info "Done!"

    # Copy kernel and initramfs
    _make_boot_on_fat
}

# Prepare efiboot.img::/EFI for "El Torito" EFI boot mode
_make_bootmode_uefi-x64.systemd-boot.eltorito() {
    _run_once _make_bootmode_uefi-x64.systemd-boot.esp
    # Set up /EFI on ISO-9660 to allow preparing an installation medium by manually copying files
    _run_once _make_efi_dir_on_iso9660
}

# Archuseriso data
_make_aui() {
    if [[ -z "${img_name}" ]]; then
        img_name="${iso_name}-${iso_version}-x64.iso"
    fi

    cp -aT --no-preserve=ownership -- "${profile}/aui/" "${isofs_dir}/aui/"
    mv -- "${isofs_dir}/aui/liveusb/persistent" "${isofs_dir}/aui/liveusb/persistent_${iso_label}"

    ### esp
    # syslinux
    if [[ -d "${isofs_dir}/syslinux" ]]; then
        install -d -m 0755 -- "${isofs_dir}/aui/liveusb/esp/"
        ln -s -- "../../../syslinux" "${isofs_dir}/aui/liveusb/esp/syslinux"
    fi

    # live kernel & initramfs
    install -d -m 0755 -- "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/x86_64/"
    install -d -m 0755 -- "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/licenses/"
    for _ucode_image in {intel-uc.img,intel-ucode.img,amd-uc.img,amd-ucode.img,early_ucode.cpio,microcode.cpio}; do
            if [[ -e "${isofs_dir}/${install_dir}/boot/${_ucode_image}" ]]; then
                ln -s -- "../../../../../${install_dir}/boot/${_ucode_image}" "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/"
            fi
    done
    if [[ -d "${isofs_dir}/${install_dir}/boot/licenses" ]]; then
        for _license in "${isofs_dir}/${install_dir}/boot/licenses/"*; do
            ln -s -- "../../../../../../${install_dir}/boot/licenses/${_license##*/}/" \
                     "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/licenses/${_license##*/}"
        done
    fi
    if [[ -f "${isofs_dir}/${install_dir}/boot/memtest" ]]; then
        ln -s -- "../../../../../${install_dir}/boot/memtest" "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/"
    fi
    for _kernel in "${isofs_dir}/${install_dir}/boot/x86_64/vmlinuz-"* \
                   "${isofs_dir}/${install_dir}/boot/x86_64/initramfs-"*".img"; do
            ln -s -- "../../../../../../${install_dir}/boot/x86_64/${_kernel##*/}" \
                  "${isofs_dir}/aui/liveusb/esp/${install_dir}/boot/x86_64/"
    done

    # persistent kernel & initramfs
    install -d -m 0755 -- "${isofs_dir}/aui/liveusb/esp/EFI/"
    for _ucode_image in {intel-uc.img,intel-ucode.img,amd-uc.img,amd-ucode.img,early_ucode.cpio,microcode.cpio}; do
        if [[ -e "${isofs_dir}/${install_dir}/boot/${_ucode_image}" ]]; then
            ln -s -- "../../../${install_dir}/boot/${_ucode_image}" "${work_dir}/iso/aui/liveusb/esp/"
        fi
    done
    for _kernel in "${isofs_dir}/${install_dir}/boot/x86_64/vmlinuz-"* \
                   "${isofs_dir}/${install_dir}/boot/x86_64/initramfs-"*".img"; do
        ln -s -- "../../../${install_dir}/boot/x86_64/${_kernel##*/}" "${work_dir}/iso/aui/liveusb/esp/"
    done
    [[ -d "${isofs_dir}/loader" ]] && ln -s -- ../../../loader "${isofs_dir}/aui/liveusb/esp/loader"
    [[ -d "${isofs_dir}/EFI/BOOT" ]] && ln -s -- ../../../../EFI/BOOT "${isofs_dir}/aui/liveusb/esp/EFI/BOOT"
    [[ -d "${isofs_dir}/EFI/live" ]] && ln -s -- ../../../../EFI/live "${isofs_dir}/aui/liveusb/esp/EFI/live"
    [[ -d "${isofs_dir}/shellx64.efi" ]] && ln -s -- ../../../shellx64.efi "${isofs_dir}/aui/liveusb/esp/shellx64.efi"

    if [[ -f "${isofs_dir}/aui/mediumdef.sh" ]]; then
        # Set medium def
        sed -i "s|%DESKTOP%|${desktop}|g;
                s|%INSTALL_DIR%|${install_dir}|g;
                s|%ARCHISO_LABEL%|${iso_label}|g;
                s|%ISO_NAME%|${iso_name}|g;
                s|%ISO_VERSION%|${iso_version}|g;
                s|%LANG%|${lang}|g" \
                "${isofs_dir}/aui/mediumdef.sh"
    fi
    for auifile in "${isofs_dir}/aui/liveusb/loader/entries/0aui-x86_64-linux.conf" \
                   "${isofs_dir}/aui/liveusb/syslinux/archiso_sys-linux.cfg" \
                   "${isofs_dir}/aui/hybrid/loader/entries/0aui-x86_64-linux.conf" \
                   "${isofs_dir}/aui/hybrid/syslinux/archiso_sys-linux.cfg"; do
        if [[ -f "${auifile}" ]]; then
            sed -i "s|%INSTALL_DIR%|${install_dir}|g;
                    s|%DESKTOP%|${desktop}|g" "${auifile}"
        fi
    done
    if [[ -n "${embed_dir}" && -d "${embed_dir}" ]]; then
        cp -aT --no-preserve=ownership "${embed_dir}" "${isofs_dir}/data"
    fi
}

_validate_requirements_bootmode_bios.syslinux.mbr() {
    # bios.syslinux.mbr requires bios.syslinux.eltorito
    # shellcheck disable=SC2076
    if [[ ! " ${bootmodes[*]} " =~ ' bios.syslinux.eltorito ' ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "Using 'bios.syslinux.mbr' boot mode without 'bios.syslinux.eltorito' is not supported." 0
    fi

    # Check if the syslinux package is in the package list
    # shellcheck disable=SC2076
    if [[ ! " ${pkg_list[*]} " =~ ' syslinux ' ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${bootmode}': The 'syslinux' package is missing from the package list!" 0
    fi

    # Check if syslinux configuration files exist
    if [[ ! -d "${profile}/syslinux" ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${bootmode}': The '${profile}/syslinux' directory is missing!" 0
    else
        local cfgfile
        for cfgfile in "${profile}/syslinux/"*'.cfg'; do
            if [[ -e "${cfgfile}" ]]; then
                break
            else
                (( validation_error=validation_error+1 ))
                _msg_error "Validating '${bootmode}': No configuration file found in '${profile}/syslinux/'!" 0
            fi
        done
    fi

    # Check for optional packages
    # shellcheck disable=SC2076
    if [[ ! " ${pkg_list[*]} " =~ ' memtest86+ ' ]]; then
        _msg_info "Validating '${bootmode}': 'memtest86+' is not in the package list. Memmory testing will not be available from syslinux."
    fi
}

_validate_requirements_bootmode_bios.syslinux.eltorito() {
    _validate_requirements_bootmode_bios.syslinux.mbr
}

_validate_requirements_bootmode_uefi-x64.systemd-boot.esp() {
    # Check if mkfs.fat is available
    if ! command -v mkfs.fat &> /dev/null; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${bootmode}': mkfs.fat is not available on this host. Install 'dosfstools'!" 0
    fi

    # Check if mmd and mcopy are available
    if ! { command -v mmd &> /dev/null && command -v mcopy &> /dev/null; }; then
        _msg_error "Validating '${bootmode}': mmd and/or mcopy are not available on this host. Install 'mtools'!" 0
    fi

    # Check if systemd-boot configuration files exist
    if [[ ! -d "${profile}/efiboot/loader/entries" ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${bootmode}': The '${profile}/efiboot/loader/entries' directory is missing!" 0
    else
        if [[ ! -e "${profile}/efiboot/loader/loader.conf" ]]; then
            (( validation_error=validation_error+1 ))
            _msg_error "Validating '${bootmode}': File '${profile}/efiboot/loader/loader.conf' not found!" 0
        fi
        local conffile
        for conffile in "${profile}/efiboot/loader/entries/"*'.conf'; do
            if [[ -e "${conffile}" ]]; then
                break
            else
                (( validation_error=validation_error+1 ))
                _msg_error "Validating '${bootmode}': No configuration file found in '${profile}/efiboot/loader/entries/'!" 0
            fi
        done
    fi

    # Check for optional packages
    # shellcheck disable=SC2076
    if [[ ! " ${pkg_list[*]} " =~ ' edk2-shell ' ]]; then
        _msg_info "'edk2-shell' is not in the package list. The ISO will not contain a bootable UEFI shell."
    fi
}

_validate_requirements_bootmode_uefi-x64.systemd-boot.eltorito() {
    # uefi-x64.systemd-boot.eltorito has the exact same requirements as uefi-x64.systemd-boot.esp
    _validate_requirements_bootmode_uefi-x64.systemd-boot.esp
}

# Build airootfs filesystem image
_prepare_airootfs_image() {
    _run_once "_mkairootfs_${airootfs_image_type}"
    _mkchecksum
    if [[ -n "${gpg_key}" ]]; then
        _mksignature
    fi
}

_validate_requirements_airootfs_image_type_squashfs() {
    if ! command -v mksquashfs &> /dev/null; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${airootfs_image_type}': mksquashfs is not available on this host. Install 'squashfs-tools'!" 0
    fi
}

_validate_requirements_airootfs_image_type_ext4+squashfs() {
    if ! { command -v mkfs.ext4 &> /dev/null && command -v tune2fs &> /dev/null; }; then
        (( validation_error=validation_error+1 ))
        _msg_error "Validating '${airootfs_image_type}': mkfs.ext4 and/or tune2fs is not available on this host. Install 'e2fsprogs'!" 0
    fi
    _validate_requirements_airootfs_image_type_squashfs
}

# SYSLINUX El Torito
_add_xorrisofs_options_bios.syslinux.eltorito() {
    xorrisofs_options+=(
        # El Torito boot image for x86 BIOS
        '-eltorito-boot' 'syslinux/isolinux.bin'
        # El Torito boot catalog file
        '-eltorito-catalog' 'syslinux/boot.cat'
        # Required options to boot with ISOLINUX
        '-no-emul-boot' '-boot-load-size' '4' '-boot-info-table'
    )
}

# SYSLINUX MBR
_add_xorrisofs_options_bios.syslinux.mbr() {
    xorrisofs_options+=(
        # SYSLINUX MBR bootstrap code; does not work without "-eltorito-boot syslinux/isolinux.bin"
        '-isohybrid-mbr' "${isofs_dir}/syslinux/isohdpfx.bin"
        # When GPT is used, create an additional partition in the MBR (besides 0xEE) for sectors 0–1 (MBR
        # bootstrap code area) and mark it as bootable
        # This violates the UEFI specification, but may allow booting on some systems
        # https://wiki.archlinux.org/index.php/Partitioning#Tricking_old_BIOS_into_booting_from_GPT
        '--mbr-force-bootable'
        # Set the ISO 9660 partition's type to "Linux filesystem data"
        # When only MBR is present, the partition type ID will be 0x83 "Linux" as xorriso translates all
        # GPT partition type GUIDs except for the ESP GUID to MBR type ID 0x83
        '-iso_mbr_part_type' '0FC63DAF-8483-4772-8E79-3D69D8477DE4'
        # Move the first partition away from the start of the ISO to match the expectations of partition
        # editors
        # May allow booting on some systems
        # https://dev.lovelyhq.com/libburnia/libisoburn/src/branch/master/doc/partition_offset.wiki
        '-partition_offset' '16'
    )
}

# systemd-boot in an attached EFI system partition
_add_xorrisofs_options_uefi-x64.systemd-boot.esp() {
    # Move the first partition away from the start of the ISO, otherwise the GPT will not be valid and ISO 9660
    # partition will not be mountable
    # shellcheck disable=SC2076
    [[ " ${xorrisofs_options[*]} " =~ ' -partition_offset ' ]] || xorrisofs_options+=('-partition_offset' '16')
    xorrisofs_options+=(
        # Attach efiboot.img as a second partition and set its partition type to "EFI system partition"
        '-append_partition' '2' 'C12A7328-F81F-11D2-BA4B-00A0C93EC93B' "${work_dir}/efiboot.img"
        # Ensure GPT is used as some systems do not support UEFI booting without it
        '-appended_part_as_gpt'
    )
}

# systemd-boot via El Torito
_add_xorrisofs_options_uefi-x64.systemd-boot.eltorito() {
    # shellcheck disable=SC2076
    if [[ " ${bootmodes[*]} " =~ ' uefi-x64.systemd-boot.esp ' ]]; then
        # systemd-boot in an attached EFI system partition via El Torito
        xorrisofs_options+=(
            # Start a new El Torito boot entry for UEFI
            '-eltorito-alt-boot'
            # Set the second partition as the El Torito UEFI boot image
            '-e' '--interval:appended_partition_2:all::'
            # Boot image is not emulating floppy or hard disk; required for all known boot loaders
            '-no-emul-boot'
        )
    else
        # The ISO will not contain a GPT partition table, so to be able to reference efiboot.img, place it as a
        # file inside the ISO 9660 file system
        install -d -m 0755 -- "${isofs_dir}/EFI/archiso"
        cp -a -- "${work_dir}/efiboot.img" "${isofs_dir}/EFI/archiso/efiboot.img"
        # systemd-boot in an embedded efiboot.img via El Torito
        xorrisofs_options+=(
            # Start a new El Torito boot entry for UEFI
            '-eltorito-alt-boot'
            # Set efiboot.img as the El Torito UEFI boot image
            '-e' 'EFI/archiso/efiboot.img'
            # Boot image is not emulating floppy or hard disk; required for all known boot loaders
            '-no-emul-boot'
        )
    fi
    # Specify where to save the El Torito boot catalog file in case it is not already set by bios.syslinux.eltorito
    # shellcheck disable=SC2076
    [[ " ${bootmodes[*]} " =~ ' bios.' ]] || xorrisofs_options+=('-eltorito-catalog' 'EFI/boot.cat')
}

# Build ISO
_build_iso() {
    local xorrisofs_options=()
    local bootmode

    [[ -d "${out_dir}" ]] || install -d -- "${out_dir}"

    [[ "${quiet}" == "y" ]] && xorrisofs_options+=('-quiet')

    # Add required xorrisofs options for each boot mode
    for bootmode in "${bootmodes[@]}"; do
        typeset -f "_add_xorrisofs_options_${bootmode}" &> /dev/null && "_add_xorrisofs_options_${bootmode}"
    done
    
    _msg_info "Creating ISO image..."
    if [[ "${quiet}" == "y" ]]; then
        xorriso -as mkisofs \
            -iso-level 3 \
            -full-iso9660-filenames \
            -joliet \
            -joliet-long \
            -volid "${iso_label}" \
            -appid "${iso_application}" \
            -publisher "${iso_publisher}" \
            -preparer "prepared by ${app_name}" \
            "${xorrisofs_options[@]}" \
            -output "${out_dir}/${img_name}" \
            "${isofs_dir}/" 2> /dev/null
    else
        xorriso -as mkisofs \
            -iso-level 3 \
            -full-iso9660-filenames \
            -joliet \
            -joliet-long \
            -volid "${iso_label}" \
            -appid "${iso_application}" \
            -publisher "${iso_publisher}" \
            -preparer "prepared by ${app_name}" \
            "${xorrisofs_options[@]}" \
            -output "${out_dir}/${img_name}" \
            "${isofs_dir}/"
    fi
    _mkchecksum_iso
    if [[ -n "${gpg_key}" ]]; then
        _mksignature_iso
    fi
    _msg_info "Done!"
    echo
    _msg_info "$(du -h -- "${out_dir}/${img_name}")"
}

_iso_version_options() {
    if grep -q optimus <<< "${iso_version_options[@]}"; then
        iso_version_options=(${iso_version_options[@]/nvidia})
    fi
    iso_version_options=($(sed 's/\s/\n/g' <<< "${iso_version_options[@]}" | sort | sed ':a;N;$!ba;s/\n/-/g'))
}

# Read profile's values from profiledef.sh
_read_profile() {
    if [[ -z "${profile}" ]]; then
        _msg_error "No profile specified!" 1
    fi
    if [[ ! -d "${profile}" ]]; then
        _msg_error "Profile '${profile}' does not exist!" 1
    elif [[ ! -e "${profile}/profiledef.sh" ]]; then
        _msg_error "Profile '${profile}' is missing 'profiledef.sh'!" 1
    else
        cd -- "${profile}"

        # Source profile's variables
        source "${profile}/profiledef.sh"

        # Resolve paths of files that are expected to reside in the profile's directory
        [[ -n "${packages}" ]] || packages="${profile}/packages.${arch}"
        packages="$(realpath -- "${packages}")"
        if [[ -n "${lang}" ]]; then
          packages_locales="$(realpath -- "${profile}/lang/${lang}/packages.${arch}")"
        fi
        pacman_conf="$(realpath -- "${pacman_conf}")"
        [[ -n "${pacman_testing_conf}" ]] && pacman_testing_conf="$(realpath -- "${pacman_testing_conf}")"

        cd -- "${OLDPWD}"
    fi
}

# Validate set options
_validate_options() {
    local validation_error=0 bootmode
    local pkg_list_from_file=()
    _msg_info "Validating options..."
    # Check if the package list file exists and read packages from it
    if [[ -e "${packages}" ]]; then
        mapfile -t pkg_list_from_file < <(sed '/^[[:blank:]]*#.*/d;s/#.*//;/^[[:blank:]]*$/d;s/[[:blank:]]/\n/g' "${packages}" "${packages_locales}" | sed '/^$/d')
        if (( ${#pkg_list_from_file} < 1 )); then
            (( validation_error=validation_error+1 ))
            _msg_error "No package specified in '${packages}'." 0
        fi
        pkg_list+=("${pkg_list_from_file[@]}")
        pkg_list+=("${pkg_list_additions[@]}")
    else
        (( validation_error=validation_error+1 ))
        _msg_error "No package specified in '${packages}'." 0
    fi

    # Check if pacman configuration file exists
    if [[ ! -e "${pacman_conf}" ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "File '${pacman_conf}' does not exist." 0
    fi
    # Check if pacman-testing configuration file exists
    if [[ -n "${pacman_testing_conf}" && ! -e "${pacman_testing_conf}" ]]; then
        (( validation_error=validation_error+1 ))
        _msg_error "File '${pacman_testing_conf}' does not exist." 0
    fi
    # Check if the specified bootmodes are supported
    for bootmode in "${bootmodes[@]}"; do
        if typeset -f "_make_bootmode_${bootmode}" &> /dev/null; then
            if typeset -f "_validate_requirements_bootmode_${bootmode}" &> /dev/null; then
                "_validate_requirements_bootmode_${bootmode}"
            else
                _msg_warning "Function '_validate_requirements_bootmode_${bootmode}' does not exist. Validating the requirements of '${bootmode}' boot mode will not be possible."
            fi
        else
            (( validation_error=validation_error+1 ))
            _msg_error "${bootmode} is not a valid boot mode!" 0
        fi
    done
    # Check if the specified airootfs_image_type is supported
    if typeset -f "_mkairootfs_${airootfs_image_type}" &> /dev/null; then
        if typeset -f "_validate_requirements_airootfs_image_type_${airootfs_image_type}" &> /dev/null; then
            "_validate_requirements_airootfs_image_type_${airootfs_image_type}"
        else
            _msg_warning "Function '_validate_requirements_airootfs_image_type_${airootfs_image_type}' does not exist. Validating the requirements of '${airootfs_image_type}' airootfs image type will not be possible."
        fi
    else
        (( validation_error=validation_error+1 ))
        _msg_error "Unsupported image type: '${airootfs_image_type}'" 0
    fi
    if (( validation_error )); then
        _msg_error "${validation_error} errors were encountered while validating the profile. Aborting." 1
    fi
    _msg_info "Done!"
}

# set overrides from mkarchiso option parameters, if present
# Set defaults and, if present, overrides from aui-mkiso command line option parameters
_set_overrides() {
    # Set variables that have command line overrides
    if [[ -v override_work_dir ]]; then
        work_dir="${override_work_dir}"
    elif [[ -z "${work_dir}" ]]; then
        work_dir='./work'
    fi
    work_dir="$(realpath -- "${work_dir}")"
    if [[ -v override_out_dir ]]; then
        out_dir="${override_out_dir}"
    elif [[ -z "${out_dir}" ]]; then
        out_dir='./out'
    fi
    out_dir="$(realpath -- "${out_dir}")"
    if [[ -v override_pacman_conf ]]; then
        pacman_conf="${override_pacman_conf}"
    elif [[ -z "${pacman_conf}" ]]; then
        pacman_conf="/etc/pacman.conf"
    fi
    pacman_conf="$(realpath -- "${pacman_conf}")"
    if [[ -v override_pacman_testing_conf ]]; then
        pacman_testing_conf="${override_pacman_testing_conf}"
    elif [[ -z "${pacman_testing_conf}" ]]; then
        pacman_testing_conf="/etc/pacman_testing.conf"
    fi
    pacman_testing_conf="$(realpath -- "${pacman_testing_conf}")"
    if [[ -v override_iso_label ]]; then
        iso_label="${override_iso_label}"
    elif [[ -z "${iso_label}" ]]; then
        iso_label="${app_name^^}"
    fi
    if [[ -v override_iso_publisher ]]; then
        iso_publisher="${override_iso_publisher}"
    elif [[ -z "${iso_publisher}" ]]; then
        iso_publisher="${app_name}"
    fi
    if [[ -v override_iso_application ]]; then
        iso_application="${override_iso_application}"
    elif [[ -z "${iso_application}" ]]; then
        iso_application="${app_name} iso"
    fi
    if [[ -v override_install_dir ]]; then
        install_dir="${override_install_dir}"
    elif [[ -z "${install_dir}" ]]; then
        install_dir="${app_name}"
    fi
    [[ ! -v override_gpg_key ]] || gpg_key="${override_gpg_key}"
    if [[ -v override_quiet ]]; then
        quiet="${override_quiet}"
    elif [[ -z "${quiet}" ]]; then
        quiet="y"
    fi
    if [[ -v override_iso_name ]]; then
        img_name="${override_iso_name}"
    fi
}

_export_gpg_publickey() {
     gpg --batch --output "${work_dir}/pubkey.gpg" --export "${gpg_key}"
}

_make_version() {
    if [[ -z "${iso_version}" ]]; then
        iso_version="$(pacman --sysroot "${work_dir}/x86_64/airootfs" -Q linux 2> /dev/null | \
                       cut -d' ' -f2 | \
                       sed s'/\./_/g; s/_arch.*//; s/^/linux_/')${iso_version_options[0]:+-${iso_version_options[0]}}${lang:+-${lang}}-$(date +%m%d)"
    fi
    install -d -m 0755 -- "${isofs_dir}/${install_dir}"
    _msg_info "Creating files with iso version..."
    printf '%s\n' "${iso_version}" > "${airootfs_dir}/version"
    printf '%s\n' "${iso_version}" > "${isofs_dir}/${install_dir}/version"
    printf '%.1024s' "$(printf '# GRUB Environment Block\nVERSION=%s\n%s' "${iso_version}" \
           "$(printf '%0.1s' "#"{1..1024})")" > "${isofs_dir}/${install_dir}/grubenv"
    _msg_info "Done!"
    }

_make_pkglist() {
    install -d -m 0755 -- "${isofs_dir}/${install_dir}"
    _msg_info "Creating a list of installed packages on live-enviroment..."
    pacman -Q --sysroot "${airootfs_dir}" > "${isofs_dir}/${install_dir}/pkglist.${arch}.txt"
    _msg_info "Done!"
}

_build_profile() {
    # Set up essential directory paths
    airootfs_dir="${work_dir}/${arch}/airootfs"
    isofs_dir="${work_dir}/iso"
    # Create working directory
    [[ -d "${work_dir}" ]] || install -d -- "${work_dir}"
    # Write build date to file or if the file exists, read it from there
    if [[ -e "${work_dir}/build_date" ]]; then
        SOURCE_DATE_EPOCH="$(<"${work_dir}/build_date")"
    else
        printf '%s\n' "$SOURCE_DATE_EPOCH" > "${work_dir}/build_date"
    fi

    _show_config
    _run_once _make_pacman_conf
    [[ -n "${pacman_testing_conf}" ]] && _run_once _make_pacman_testing_conf
    [[ "${build_zfs_packages}" == "y" ]] && _run_once _build_zfs_packages
    [[ -z "${gpg_key}" ]] || _run_once _export_gpg_publickey
    _run_once _make_custom_airootfs
    _run_once _make_packages
    [[ -n "${pkg_testing_list[*]}" ]] && _run_once _make_packages_testing
    [[ -n "${user_pkg_dir}" && -d "${user_pkg_dir}" ]] && _run_once _make_packages_upgrade
    _run_once _make_version
    _run_once _make_customize_airootfs
    _run_once _make_setup_mkinitcpio
    _run_once _make_pkglist
    _make_bootmodes
    _run_once _cleanup_airootfs
    _run_once _make_aui
    _run_once _prepare_airootfs_image
    _run_once _build_iso
}

_build_zfs_packages () {
    if [[ "${SCRIPTUSER}" == 'root' || -z "${SUDO_USER:-}" ]]; then
        echo
        echo 'Option for ZFS support:'
        echo 'The script must be run from a _user session_ using sudo!'
        echo 'Aborting...'
        exit 0
    fi

    local _WD _auiwork _ar64 _linuxversion _modulesversion _zfspackages _zfssources _zfsversion
    local _ZFSPUBKEY _KEYSERVER
    _WD="$(pwd)"
    _auiwork="${_WD}/$(mktemp -u auiwork.XXXXXXXX)"
    _ar64="${_auiwork}/archroot64"
    _ZFSPUBKEY="6AD860EED4598027"
    _KEYSERVER="ha.pool.sks-keyservers.net"

    # Retrieve ZFS on Linux public key
    if ! sudo --user "${SCRIPTUSER}" gpg --list-public-keys "${_ZFSPUBKEY}" &> /dev/null; then
        echo
        read -r -n1 -p 'Retrieve missing ZFS on Linux public key (N/y)? '
        echo
        if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
            echo 'Operation canceled by user!'
            exit 0
        fi
        if ! sudo --user "${SCRIPTUSER}" gpg --keyserver "${_KEYSERVER}" --recv "${_ZFSPUBKEY}"; then
            echo
            echo "Retreiving ZFS public key ${_ZFSPUBKEY} failed, aborting!"
            echo
        fi
    fi

    if ! pacman -Q devtools &> /dev/null; then
        echo 'devtools package not installed, aborting!'
        exit 0
    fi
    if ! pacman -Q pacman-contrib &> /dev/null; then
        echo 'pacman-contrib package not installed, aborting!'
        exit 0
    fi
    mkdir -p -- "${_WD}/work/pkgdir"
    mkdir -p -- "${_ar64}"
    chmod a+x -- "${_auiwork}"
    mapfile -t _zfssources < <(curl --silent --retry 3 --retry-connrefused --fail -- \
                   https://api.github.com/repos/openzfs/zfs/releases/latest | \
                   grep browser_download_url | cut -d':' -f2- | sed 's/\"//g; s/^[[:blank:]]*//')
    _zfsversion="${_zfssources[0]%/zfs-*}"
    _zfsversion="${_zfsversion#*-}"
    if [[ -z "${_zfsversion}" ]]; then
        echo 'Retrieving ZFS data failed, aborting!'
        exit 0
    fi
    _msg_info "Preparing zfs chroot"
    if [[ "${quiet}" == "y" ]]; then
        mkarchroot -c /var/cache/pacman/pkg -- "${_ar64}/root" base linux linux-headers base-devel &> /dev/null
    else
        mkarchroot -c /var/cache/pacman/pkg -- "${_ar64}/root" base linux linux-headers base-devel
    fi
    _msg_info "Done!"
    if [[ -n "${pkg_testing_list[*]}" ]]; then
        for _package in "${pkg_testing_list[@]}"; do
            if [[ "${_package}" = 'linux' ]]; then
                _msg_info "Installing linux package from testing"
                if [[ "${quiet}" == "y" ]]; then
                    pacstrap -C "${work_dir}/pacman-testing.conf" -c -G -M -- "${_ar64}/root" linux linux-headers &> /dev/null
                else
                    pacstrap -C "${work_dir}/pacman-testing.conf" -c -G -M -- "${_ar64}/root" linux linux-headers
                fi
                _msg_info "Done!"
                break
            fi
        done
    fi
    _linuxversion=$(pacman --sysroot "${_ar64}/root" -Q linux | cut -d' ' -f2)
    if [[ "$(cut -d'.' -f3 <<< "${_linuxversion}")" =~ 'arch' ]]; then
        _modulesversion="${_linuxversion%.arch*}.0-${_linuxversion##*.}"
    else
        _modulesversion="${_linuxversion%.arch*}-${_linuxversion##*.}"
    fi
    cp -arT -- "${profile}/aui/zfsonlinux" "${_auiwork}/zfsonlinux"
    sed -i -- "s/%ZFSVERSION%/${_zfsversion}/
               s/%LINUXVERSION%/${_linuxversion}/
               s/%MODULESVERSION%/${_modulesversion}/" \
               "${_auiwork}/zfsonlinux/zfs-utils/PKGBUILD" \
               "${_auiwork}/zfsonlinux/zfs-linux/PKGBUILD"
    cd -- "${_auiwork}/zfsonlinux/zfs-utils/"
    for _zfslink in "${_zfssources[@]}"; do
        if [[ "${_zfslink}" =~ '.tar.gz'$ ]]; then
            curl --silent --retry 3 --retry-connrefused --fail -L -O "${_zfslink}"
            curl --silent --retry 3 --retry-connrefused --fail -L -O "${_zfslink}".asc
            break
        fi
    done
    cp -a -- zfs-*.tar.gz{,.asc} ../zfs-linux
    chown -R "${SCRIPTUSER}": -- "${_auiwork}/zfsonlinux"
    _msg_info "Creating PKGBUILDs"
    if [[ "${quiet}" == "y" ]]; then
        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD 2> /dev/null
        sudo --user "${SCRIPTUSER}" updpkgsums 2> /dev/null
    else
        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
        sudo --user "${SCRIPTUSER}" updpkgsums
    fi
    cd -- "${_auiwork}/zfsonlinux/zfs-linux/"
    if [[ "${quiet}" == "y" ]]; then
        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD 2> /dev/null
        sudo --user "${SCRIPTUSER}" updpkgsums 2> /dev/null
    else
        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
        sudo --user "${SCRIPTUSER}" updpkgsums
    fi
    _msg_info "Done!"
    cd -- "${_auiwork}/zfsonlinux/zfs-utils/"
    _msg_info "Building zfs-utils"
    if [[ "${quiet}" == "y" ]]; then
        sudo --user "${SCRIPTUSER}" \
        makechrootpkg -r "${_ar64}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar &> /dev/null
    else
        sudo --user "${SCRIPTUSER}" \
        makechrootpkg -r "${_ar64}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    fi
    _msg_info "Done!"
    mapfile -t _zfspackages < <(find -- "${_auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
    cd -- "${_auiwork}/zfsonlinux/zfs-linux/"
    _msg_info "Building zfs-linux"
    if [[ "${quiet}" == "y" ]]; then
        sudo --user "${SCRIPTUSER}" \
        makechrootpkg -r "${_ar64}" -I "${_zfspackages[0]}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar &> /dev/null
    else
        sudo --user "${SCRIPTUSER}" \
        makechrootpkg -r "${_ar64}" -I "${_zfspackages[0]}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    fi
    _msg_info "Done!"
    mapfile -t _zfspackages < <(find -- "${_auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
    if [[ -n "${user_pkg_dir}" ]]; then
        cp -- "${_zfspackages[@]}" "${user_pkg_dir}"
    else
        cp -- "${_zfspackages[@]}" "${_WD}/work/pkgdir"
        user_pkg_dir="${_WD}/work/pkgdir"
    fi
    rm -r -- "${_auiwork}"
    cd -- "${_WD}"
}

OPTS=$(getopt -o '?A:C:D:g:hL:l:N:o:P:p:vw:' \
              -l 'addi3wm,addpkg:,addpkgtesting:,application:,embeddir:' \
              -l 'add-i3-wm,add-pkg:,add-pkg-testing:,embed-dir:' \
              -l 'gpgkey:,installdir:,label:,language:,nvidia,optimus' \
              -l 'outdir:,pacman-testing-conf:,pkgdir:,publisher:' \
              -l 'install-dir:,out-dir:,pacmantestingconf:,pkg-dir:' \
              -l 'verbose,workdir:,work-dir:,zfs' \
              -l 'help' \
              -n "${app_name}" -- "$@")
[[ $? -eq 0 ]] || _usage 1
eval set -- "${OPTS}"
unset OPTS

while true; do
    case "${1}" in
        '-?'|'-h'|'--help')
            _usage 0 ;;
        '-p'|'--add-pkg'|'--addpkg')
            pkg_list_additions+=($(tr ',' ' ' <<< "${2}"))
            shift 2 ;;
        '--add-pkg-testing'|'--addpkgtesting')
            pkg_testing_list=($(tr ',' ' ' <<< "${2}"))
            shift 2 ;;
        '-A'|'--application')
            override_iso_application="${2}"
            shift 2 ;;
        '--add-i3-wm'|'--addi3wm')
            pkg_list_additions+=(i3-gaps feh dmenu i3status wmctrl rxvt-unicode)
            iso_version_options+=(i3)
            shift ;;
        '-C')
            override_pacman_conf="$(realpath -- "${2}")"
            shift 2 ;;
        '-D'|'--install-dir'|'--installdir')
            override_install_dir="${2}"
            shift 2 ;;        
        '--embed-dir'|'--embeddir')
            embed_dir="${2}"
            shift 2 ;;
        '-g'|'--gpgkey')
            override_gpg_key="${2}"
            shift 2 ;;
        '-L'|'--label')
            override_iso_label="${2}"
            shift 2 ;;
        '-l'|'--language')
            case "${2}" in
                'cz'|'cs_CZ') lang="cs_CZ";;
                'de'|'de_DE') lang="de_DE";;
                'es'|'es_ES') lang="es_ES";;
                'fr'|'fr_FR') lang="fr_FR";;
                'gr'|'el_GR') lang="el_GR";;
                'hu'|'hu_HU') lang="hu_HU";;
                'it'|'it_IT') lang="it_IT";;
                'nl'|'nl_NL') lang="nl_NL";;
                'pl'|'pl_PL') lang="pl_PL";;
                'pt'|'pt_PT') lang="pt_PT";;
                'ro'|'ro_RO') lang="ro_RO";;
                'rs'|'sr_RS@latin') lang="sr_RS@latin";;
                'ru'|'ru_RU') lang="ru_RU";;
                'tr'|'tr_TR') lang="tr_TR";;
                'ua'|'uk_UA') lang="uk_UA";;
                *) _usage 1;;
            esac
            shift 2 ;;
        '-N'|'--name')
            override_iso_name="${2}"
            shift 2 ;;
        '--nvidia')
            pkg_list_additions+=(nvidia nvidia-settings bbswitch)
            iso_version_options+=(nvidia)
            shift ;;
        '--optimus')
            pkg_list_additions+=(nvidia nvidia-settings nvidia-prime)
            iso_version_options+=(optimus)
            shift ;;
        '-o'|'--out-dir'|'--outdir')
            override_out_dir="${2}"
            shift 2 ;;
        '--pacman-testing-conf'|'--pacmantestingconf')
            override_pacman_testing_conf="$(realpath -- "${2}")"
            shift 2 ;;
        '--pkg-dir'|'--pkgdir')
            user_pkg_dir="${2}"
            shift 2 ;;
        '-P'|'--publisher')
            override_iso_publisher="${2}"
            shift 2 ;;
        '-v'|'--verbose')
            override_quiet="n"
            shift ;;
        '-w'|'--workdir'|'--work-dir')
            override_work_dir="${2}"
            shift 2 ;;
        '--zfs')
            build_zfs_packages="y"
            iso_version_options+=(zfs)
            shift ;;
        '--')
            shift
            break ;;
    esac
done

if [[ $# -eq 0 ]]; then
    _msg_error "No profile specified" 0
    _usage 1
fi
if (( EUID != 0 )); then
    _msg_error "${app_name} must be run as root." 1
fi

if [[ ! -d "$(realpath -- "${1}")" ]]; then
    set -- "${directory_profiles}/${1}"
fi
profile="$(realpath -- "${1}")"

[[ -n "${iso_version_options[*]}" ]] && _iso_version_options
_read_profile
_set_overrides
echo
if [[ -d "${work_dir}" ]]; then
    _msg_info "WORKING DIRECTORY '${work_dir}' ALREADY EXISTS! REMOVE DIRECTORY BEFORE BUILDING A NEW ISO." && 
    echo
    exit 0
fi
_validate_options
_build_profile
_msg_info "Success!"

# vim:ts=4:sw=4:et:
