#!/usr/bin/env bash
#
# Copyright (C) 2024 Laurent Jourden <laurent85@enarel.fr>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Compress an Arch Linux system to a bootable disk image.

set -e -u

appname="${0##*/}"
linux_release=""
aui_suffix="$(mktemp -u _XXX)"
ro_label="RO${aui_suffix}"
esp_label="ESP${aui_suffix}"
cow_label="COW${aui_suffix}"
loopdevice=""
outdir="${PWD}/out"
profile="/usr/share/archuseriso/hd2aui"
wd="${PWD}"
workdir="$(mktemp -u auiwork.XXXXXXXX)"

_help() {
    echo
    echo "${appname}: Compress an Arch Linux system to a bootable disk image."
    echo
    echo 'Synopsis:'
    echo "${appname} [options] <path to root filesystem>"
    echo
    echo
    echo 'Options:'
    echo '-h, --help                  Command line help'
    echo "-w, --workdir               Set the Working directory (default: ${wd}/auiwork.XXXXXXXX)"
    echo "-o, --outdir                Set the output directory (default: ${wd}/out)"
    echo "--config                    Path to hd2aui configuration files (default: ${profile})"
    echo
    exit "${1}"
}

_msg_info() {
    local _msg="${1}"
    printf '[%s] INFO: %s\n' "${appname}" "${_msg}"
}

# Show an ERROR message then exit with status
# $1: message string
# $2: exit code number (with 0 does not exit)
_msg_error() {
    local _msg="${1}"
    local _error=${2}
    printf '[%s] ERROR: %s\n' "${appname}" "${_msg}" >&2
    if (( _error > 0 )); then
        exit "${_error}"
    fi
}

_cleanup() {
    local _workdirs
    _workdirs=('imgp1' 'imgp2' 'overlay' 'rootfsbind')
    for _workdir in "${_workdirs[@]}"; do
        if mountpoint -q -- "${workdir}/${_workdir}"; then
            umount -- "${workdir}/${_workdir}" || exit 1
        fi
    done
    if [[ -d "${workdir}" ]]; then
        rm -r -- "${workdir}"
    fi
}

_unmount() {
    echo
    _msg_info "Unmount working directories, may take some time"
    _cleanup
    _msg_info "Done!"
}

_check() {
    if [[ $# -ne 1 ]]; then
        _msg_error 'Error: Invalid arguments!' 1
    fi
    if [[ ${EUID} -ne 0 ]]; then
        _msg_error 'This script must be run as root!' 1
    fi
    rootfs_path="${1}"

    # the command argument is a valid directory path
    [[ -d "${rootfs_path}" ]] || _msg_error "${rootfs_path} is not a valid directory path!" 1
    [[ -d "${wd}" ]] || _msg_error "${wd} is not a valid directory path!" 1
    [[ -d "${outdir}" ]] ||  _msg_error "${outdir} is not a valid directory path!" 1
    workdir="${wd}/${workdir}"

    # rootfs is an Arch Linux system
    if [[ ! -f "${rootfs_path}/usr/share/factory/etc/issue" ]]; then
        _msg_error "Does not look like a valid Arch Linux root filesystem!" 0
        _msg_error "/usr/share/factory/etc/issue: File not found!" 1
    fi
    if ! grep -q 'Arch Linux' "${rootfs_path}/usr/share/factory/etc/issue"; then
        _msg_error "Does not look a valid Arch Linux root filesystem!" 0
        _msg_error "/usr/share/factory/etc/issue: Invalid content!" 0
        _msg_error "Can't proceed" 1
    fi
    [[ -f "${rootfs_path}/etc/mkinitcpio.conf" ]] || _msg_error "/etc/mkinitcpio.conf is missing! Aborting" 1
  
    # rootfs is not the running system
    (( $(stat --format=%i /usr/lib/systemd/systemd) != \
       $(stat --format=%i "${rootfs_path}/usr/lib/systemd/systemd") )) || \
       _msg_error "The root filesystem path argument is the running system! Cannot proceed, aborting." 1

    # Set hd2aui profile path
    [[ -d "${profile}" ]] || _msg_error "Some Archuseriso files are missing. Install Archuseriso! Aborting." 1
    [[ -d "${profile}/airootfs" ]] || _msg_error "${profile} is not a valid hd2aui configuration path! Aborting." 1
    [[ -d "${profile}/esp" ]] || _msg_error "${profile} is not a valid hd2aui configuration path! Aborting." 1

    # linux package installed
    if ! eval -- env -u TMPDIR arch-chroot "${rootfs_path}" pacman -Q linux &> /dev/null; then
        _msg_error "linux package not installed! Aborting." 1
    fi
    linux_release="$(eval -- env -u TMPDIR arch-chroot "${rootfs_path}" pacman -Q linux 2> /dev/null | awk '{print $2}')"
    grep -q -E -- '^[[:digit:]]{1,2}\.[[:digit:]]{1,}\.[[:digit:]]{1,3}' <<< "${linux_release}" ||
        linux_release="${linux_release%arch*}0-${linux_release##*.}"

    # calculate filesystem size, set limit to 20G
    if (( $(du -B1G -s "${rootfs_path}" | awk '{print $1}') > 20 )); then
        _msg_error "Filesystem size exceeds 20G limit! aborting." 1
    fi

    if ! pacman -Q syslinux &> /dev/null; then
        _msg_error "syslinux package not installed! Aborting." 1
    fi
}

_confirm() {
    echo
    _msg_info "Path to root filesystem:   ${rootfs_path}"
    echo
    read -r -n1 -p "Confirm operation (N/y)? "
    echo
    if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
        echo 'Operation canceled by user!'
        exit 0
    fi
}

_overlayfs() {
    local _lines=0 _archiso=""
    local -a _hooks=() _packages=()

    # overlay fs setup
    _msg_info "Preparing the overlay filesystem"

    # check & prepare working directory
    for mountpoint in "${workdir}/"{rootfsbind,overlay}; do
        if findmnt -nr -- "${mountpoint}" > /dev/null; then
            _msg_error "${mountpoint} appears in active mounts, unmount before proceeding!" 1
        fi
    done
    for mountpoint in "${workdir}/"{rootfsbind,overlay}; do
        if [[ -e "${mountpoint}" ]]; then
            _msg_error "${mountpoint} exists in working directory! Delete or rename before proceeding!" 1
        fi
    done
    install -d -m 0755 -- "${workdir}/"{rootfsbind,esp,overlay,overlayup,overlaywork}

    # recursive bind mount read-only the rootfs 
    if ! mount --options=rbind,ro=recursive -- "${rootfs_path}" "${workdir}/rootfsbind"; then
        _msg_error "Bind mount of root filesystem failed! Aborting." 1
    fi
    # Mount overlay filesystem
    if ! mount --types=overlay overlay \
               --options=lowerdir="${workdir}/rootfsbind",upperdir="${workdir}/overlayup",workdir="${workdir}/overlaywork" -- \
               "${workdir}/overlay"; then
        _msg_error "Mounting overlay filesystem failed! Aborting." 1
    fi
    _msg_info "Done!"

    _msg_info "Configuring overlay filesystem for live startup"
    # copy linux kernel to /boot overlay
    if [[ ! -f "${workdir}/overlay/boot/vmlinuz-linux" ]]; then
        install -m 0644 -- "${workdir}/overlay/usr/lib/modules/${linux_release}/vmlinuz" "${workdir}/overlay/boot/vmlinuz-linux"
    fi
 
    # add archiso hooks to mkinitcpio.conf
    _lines=$(sed -n -- '/^HOOKS=/p' "${workdir}/overlay/etc/mkinitcpio.conf" | wc -l)
    (( _lines > 1 || _lines == 0 )) && _msg_error 'Invalid mkinitcpio.conf! HOOKS line missing or duplicates. Aborting.' 1

    # shellcheck source=/dev/null
    source "${workdir}/overlay/etc/mkinitcpio.conf"
    for ((i=0; i < "${#HOOKS[@]}"; i++)); do
        [[ "${HOOKS[${i}]}" = 'archiso' ]] && _archiso="yes"
        ! [[ "${HOOKS[${i}]}" = 'autodetect' ]] && _hooks+=("${HOOKS[${i}]}")
    done
    ! [[ "${HOOKS[*]}" =~ 'microcode' ]] && _hooks+=('microcode')
    ! [[ "${_archiso}" = "yes" ]] && _hooks+=('archiso')
    ! [[ "${HOOKS[*]}" =~ 'memdisk' ]] && _hooks+=('memdisk')
    for hk in archiso_loop_mnt archiso_pxe_common archiso_pxe_http archiso_pxe_nbd archiso_pxe_nfs; do
        ! [[ "${_hooks[*]}" =~ "${hk}" ]] && _hooks+=("${hk}")
    done
    sed -i -- "s/^HOOKS=.*/HOOKS=(${_hooks[*]})/" "${workdir}/overlay/etc/mkinitcpio.conf"
    _msg_info "Done!"

    _msg_info "Installing necessary packages to overlay filesystem"
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q mkinitcpio-archiso &> /dev/null || _packages+=('mkinitcpio-archiso')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q nbd &> /dev/null || _packages+=('nbd')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q mkinitcpio-nfs-utils &> /dev/null || _packages+=('mkinitcpio-nfs-utils')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q amd-ucode &> /dev/null || _packages+=('amd-ucode')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q intel-ucode &> /dev/null || _packages+=('intel-ucode')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q limine &> /dev/null || _packages+=('limine')
    eval -- env -u TMPDIR arch-chroot "${workdir}/overlay" pacman -Q syslinux &> /dev/null || _packages+=('syslinux')
    eval -- env -u TMPDIR pacstrap -c -G -M -- "${workdir}/overlay" "${_packages[@]}" &> /dev/null || \
        _msg_error "Could not install ${_packages[@]} to overlay! Aborting." 1
    _msg_info "Done!"

    _msg_info "Configuring boot files"
    # copy airootfs files to overlay
    if [[ -d "${profile}/airootfs" ]]; then
        cp -af --no-preserve=ownership -- "${profile}/airootfs/." "${workdir}/overlay/"
    else
        _msg_error "Some Archuseriso files are missing. Install Archuseriso! Aborting." 1
    fi

    # Set archiso cow size to 50% ram size
    sed -i 's|\(cow_spacesize=\)"256M"|\1"$(( $(awk \x27/MemTotal:/ { print $2 }\x27 /proc/meminfo) / 2 / 1024 ))M"|;
            s|\(&& copytoram=\)"auto"|\1"no"|' "${workdir}/overlay/etc/initcpio/hooks/archiso"

    # generate initramfs
    env -u TMPDIR arch-chroot "${workdir}/overlay" mkinitcpio -P &> /dev/null || \
        _msg_error 'Making initramfs failed! Aborting.' 1

    # copy esp profile to workdir
    if [[ -d "${profile}/esp" ]]; then
        cp -af --no-preserve=ownership -- "${profile}/esp/." "${workdir}/esp/"
    else
        _msg_error "Some Archuseriso files are missing. Install Archuseriso! Aborting." 1
    fi

    # copy limine bootloader files to esp
    install -m 0644 -- "${workdir}/overlay/usr/share/limine/limine-bios.sys" "${workdir}/esp/"
    install -d -m 0755 -- "${workdir}/esp/EFI/BOOT/"
    install -m 0644 -- "${workdir}/overlay/usr/share/limine/BOOTX64.EFI" "${workdir}/esp/EFI/BOOT/"


    # copy syslinux bootloader files
    install -m 0644 -- "${workdir}/overlay/usr/lib/syslinux/bios/"*.c32 "${workdir}/esp/syslinux/"
    install -m 0644 -- "${workdir}/overlay/usr/lib/syslinux/bios/lpxelinux.0" "${workdir}/esp/syslinux/"
    install -m 0644 -- "${workdir}/overlay/usr/lib/syslinux/bios/memdisk" "${workdir}/esp/syslinux/"

    if [[ -e "${workdir}/esp/syslinux/hdt.c32" ]]; then
        install -d -m 0755 -- "${workdir}/esp/syslinux/hdt"
        if [[ -e "${workdir}/overlay/usr/share/hwdata/pci.ids" ]]; then
            gzip -cn9 "${workdir}/overlay/usr/share/hwdata/pci.ids" > "${workdir}/esp/syslinux/hdt/pciids.gz"
        fi
        find "${workdir}/overlay/usr/lib/modules" -name 'modules.alias' -print -exec gzip -cn9 '{}' ';' -quit > \
            "${workdir}/esp/syslinux/hdt/modalias.gz"
    fi

    # set boot parameters
    sed -i -- "s|%RO_LABEL%|${ro_label}|;s|%COW_LABEL%|${cow_label}|" "${workdir}/esp/limine.cfg" || \
       _msg_error "Limine configuration file setup failed! Aborting." 1
    sed -i -- "s|%RO_LABEL%|${ro_label}|;s|%COW_LABEL%|${cow_label}|" "${workdir}/esp/syslinux/archiso_sys-linux.cfg" || \
       _msg_error "Syslinux configuration file setup failed! Aborting." 1
    sed -i -- "s|%ESP_LABEL%|${esp_label}|" "${workdir}/overlay/etc/fstab" || \
       _msg_error "fstab configuration file setup failed! Aborting." 1
 
    # copy linux kernel and initramfs to esp
    install -d -m 0755 -- "${workdir}/esp/arch/boot/x86_64/"
    install -m 0644 -- "${workdir}/overlay/boot/vmlinuz-linux" "${workdir}/esp/arch/boot/x86_64/"
    install -m 0644 -- "${workdir}/overlay/boot/initramfs-linux.img" "${workdir}/esp/arch/boot/x86_64/"
    _msg_info "Done!"

    _msg_info "Filesystem cleanup"
    # Delete unnecessary files in overlay /boot
    [[ -d "${workdir}/overlay/boot" ]] && find "${workdir}/overlay/boot" -mindepth 1 -delete
    # Delete pacman package cache
    [[ -d "${workdir}/overlay/var/cache/pacman/pkg" ]] && find "${workdir}/overlay/var/cache/pacman/pkg" -type f -delete
    # Delete all log files, keeps empty dirs.
    [[ -d "${workdir}/overlay/var/log" ]] && find "${workdir}/overlay/var/log" -type f -delete
    # Delete all temporary files and dirs
    [[ -d "${workdir}/overlay/var/tmp" ]] && find "${workdir}/overlay/var/tmp" -mindepth 1 -delete
    # Create /etc/machine-id with special value 'uninitialized': the final id is
    # generated on first boot, systemd's first-boot mechanism applies (see machine-id(5))
    rm -f -- "${workdir}/overlay/etc/machine-id"
    printf 'uninitialized\n' > "${workdir}/overlay/etc/machine-id"
    _msg_info "Done!"

    _msg_info "Creating the compressed filesystem image"
    # make squashfs image
    mksquashfs "${workdir}/overlay/" "${workdir}/airootfs.sfs" -noappend -comp zstd -quiet 2> /dev/null || \
        _msg_error "Making squashfs image failed! Aborting." 1
    _msg_info "Done!"
}

_diskimage() {
    local _rosize=0 _espsize=0 _cowsize=0

    image_name="hd2aui-$(date +%m%d)${aui_suffix/_/-}.img"

    [[ -d "${outdir}" ]] || install -d -m 0755 -- "${outdir}"

    rm -f -- "${outdir}/${image_name}"
    _msg_info "Creating the GPT disk image..."

    # ESP size in MiB
    _espsize=512

    # Read-only fs size in MiB (squashfs image size + ext4 overhead)
    _rosize=$(( $(du -B1M -s -- "${workdir}/airootfs.sfs" | awk '{print $1}') + 192 ))

    # COW size = 128 MiB
    _cowsize=128

    # IMG size = ESP + RO + COW
    # Create IMG file
    truncate -s $(( _espsize + _rosize + _cowsize + 2 ))M -- "${outdir}/${image_name}" || \
        _msg_error "Disk image creation failed! Aborting." 1

    # GPT partitions
    loopdevice=$(losetup -f --show "${outdir}/${image_name}" 2> /dev/null || \
                _msg_error "Loop device setup failed! Aborting" 1)
    if ! echo 'label: gpt' | udevadm lock --device="${loopdevice}" -- \
       sfdisk -W always -- "${loopdevice}" &> /dev/null; then
        _msg_error "GPT partition table setup failed! Aborting" 1
    fi
    if ! echo -e ",${_espsize}MiB,EBD0A0A2-B9E5-4433-87C0-68B6B72699C7,\n,${_rosize}MiB,L,\n,+,L,\n" | \
            udevadm lock --device="${loopdevice}" -- sfdisk --append  -W always -- "${loopdevice}" &> /dev/null; then
        _msg_error "Partitionning the disk image failed! Aborting." 1
    fi
    sleep 3
    partprobe -- "${loopdevice}"

    if ! udevadm lock --device="${loopdevice}p1" -- \
            mkfs.fat -F32 -n "ESP${aui_suffix}" -- "${loopdevice}p1" &> /dev/null; then
        _msg_error "Formating partition #1 failed!" 1
    fi
    if ! udevadm lock --device="${loopdevice}p2" -- \
            mkfs.ext4 -L "RO${aui_suffix}" -m0 -q -T largefile4 -- "${loopdevice}p2" &> /dev/null; then
        _msg_error "Formating partition #2 failed!" 1
    fi
    if ! udevadm lock --device="${loopdevice}p3" -- \
            mkfs.ext4 -L "COW${aui_suffix}" -O encrypt -q -- "${loopdevice}p3" &> /dev/null; then
        _msg_error "Formating partition #3 failed!" 1
    fi
    _msg_info "Done!"

    _msg_info "Copying the live filesystem and boot files to the GPT disk image..."
    # Mount disk image partitions
    install -d -m 0755 -- "${workdir}/imgp1"
    install -d -m 0755 --  "${workdir}/imgp2"
    mount --type=vfat -- "${loopdevice}p1" "${workdir}/imgp1"
    mount --type=ext4 -- "${loopdevice}p2" "${workdir}/imgp2"
    install -d -m 0755 -- "${workdir}/imgp2/arch/x86_64"

    # Copy filesystem to image disk
    install -m 0755 -- "${workdir}/airootfs.sfs" "${workdir}/imgp2/arch/x86_64/"
    cp -af --no-preserve=ownership -- "${workdir}/esp/." "${workdir}/imgp1/"

    # persistent kernel & initramfs
    install -m 0644 -- "${workdir}/esp/arch/boot/x86_64/"{vmlinuz-linux,initramfs-linux.img} "${workdir}/imgp1/"
    _msg_info "Done!"
}

_biosbootloader() {
    # copy syslinux bootloader files to esp

    _msg_info "Installing Syslinux bootloader to the GPT disk image..."
    if ! syslinux --directory syslinux --install -- "${loopdevice}p1" &> /dev/null; then
        _msg_error 'Syslinux bootloader installation failed!' 1
    fi
    if ! dd bs=440 count=1 conv=notrunc if="${workdir}/overlay/usr/lib/syslinux/bios/gptmbr.bin" of="${loopdevice}" 2> /dev/null; then
        _msg_error 'Syslinux bootloader installation failed!' 1
    fi
    if ! sfdisk --lock --part-attrs "${loopdevice}" 1 LegacyBIOSBootable &> /dev/null; then
        _msg_error 'Syslinux bootloader installation failed!' 1
    fi
    _msg_info "Done!"

    # Unmount all
    _unmount

    # Remove loop device
    losetup -d "${loopdevice}"
}

# arguments
OPTS=$(getopt -o 'h,o,w' --long 'help,config:,outdir:,workdir:' -n "${appname}" -- "$@")
[[ $? -eq 0 ]] || _help 1
eval set -- "${OPTS}"
unset OPTS
[[ $# -eq 1 ]] && _help 1

while true; do
    case "${1}" in
        '-h'|'--help')
            _help 0 ;;
        '--config')
            profile="${2}"
            shift 2 ;;
        '-o'|'--outdir')
            outdir="${2}"
            shift 2 ;;
        '-w'|'--workdir')
            wd="${2}"
            shift 2 ;;
        '--')
            shift
            break ;;
    esac
done

trap _cleanup EXIT
_check "$@"
_confirm
_overlayfs
_diskimage
_biosbootloader
echo
_msg_info "Success!"
 echo
_msg_info "$(du -BM -s -- "${outdir}/${image_name}")"

# vim:ts=4:sw=4:et:
