#!/bin/sh

if [ -z "$1" ]; then
  exit 0
fi

# Samba services may need a restart upon new NM connection
case "$2" in
  up|vpn-up)
    systemctl -q is-active smb     && systemctl restart smb
    systemctl -q is-active nmb     && systemctl restart nmb
    systemctl -q is-active winbind && systemctl restart winbind
    ;;
esac
